[package]
name = "min-rt"
version = "0.1.0"
edition = "2021"
repository = ""
categories = ["graphics", "rendering"]

[dependencies]
cgmath = "0.18.0"
yaml-rust = "0.4.5"

[workspace]
members = [
    "examples/*"
]
